apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: phoenix

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: taskapp-frontend:v6

        imagePullPolicy: Never
        ports:
        - containerPort: 80
