apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: phoenix

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: ghcr.io/ts-a-devops/taskapp-backend@sha256:7ebe1b93baef2c95098d6ce253879b4067ffbe39645a9c4fa5513aff202e4a70
        imagePullPolicy: Always

        ports:
        - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

        env:
        - name: DATABASE_HOST
          value: postgres

        - name: DATABASE_PORT
          value: "5432"

        - name: DATABASE_NAME
          value: taskapp

        - name: DATABASE_USER
          value: taskapp_user

        - name: DATABASE_PASSWORD
          value: taskapp_password

        - name: SECRET_KEY
          value: dev-secret-key-change-in-production
